<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vgl</string>
	</array>
	<key>name</key>
	<string>Virgil</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.vgl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>(#).*?$\n?</string>
			<key>name</key>
			<string>comment.line.pound.vgl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.struct.vgl</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.struct.vgl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.vgl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(struct)\s+([a-zA-Z0-9]+)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(extern|return|if|else|while|for|downto|upto|break|continue|import)\b</string>
			<key>name</key>
			<string>keyword.control.vgl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Types</string>
			<key>match</key>
			<string>\b(void|func|list|lambda|bool|int|float|str)\b</string>
			<key>name</key>
			<string>storage.type.vgl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>User type</string>
			<key>match</key>
			<string>\b[A-Z][a-zA-Z0-9]*\b</string>
			<key>name</key>
			<string>storage.type.vgl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Types</string>
			<key>match</key>
			<string>\b(export|let|out|mut)\b</string>
			<key>name</key>
			<string>storage.modifier.vgl</string>
		</dict>
		<dict>
			<key>comment</key>
			<false/>
			<key>match</key>
			<string>\bnull\b</string>
			<key>name</key>
			<string>constant.language.null.vgl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>New</string>
			<key>match</key>
			<string>\bnew\b</string>
			<key>name</key>
			<string>constant.language.new.vgl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Generic params</string>
			<key>match</key>
			<string>\'[A-Z]</string>
			<key>name</key>
			<string>constant.language.null.vgl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Generic params</string>
			<key>match</key>
			<string>\bdefault\b</string>
			<key>name</key>
			<string>storage.type.vgl</string>
		</dict>
		<dict>
			<key>comment</key>
			<true/>
			<key>match</key>
			<string>\btrue\b</string>
			<key>name</key>
			<string>constant.language.boolean.true.vgl</string>
		</dict>
		<dict>
			<key>comment</key>
			<false/>
			<key>match</key>
			<string>\bfalse\b</string>
			<key>name</key>
			<string>constant.language.boolean.true.vgl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operators</string>
			<key>match</key>
			<string>\+|\-|/|\*\*|\*</string>
			<key>name</key>
			<string>keyword.operator.vgl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.vgl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.vgl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.vgl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(t|n|r|")</string>
					<key>name</key>
					<string>constant.character.escape.vgl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.function.vgl</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.vgl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.vgl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Functions</string>
			<key>match</key>
			<string>(function|method)\s+([a-zA-Z0-9]+)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.vgl</string>
	<key>uuid</key>
	<string>35baef2b-fb03-4b10-8ecd-4a979c8cd213</string>
</dict>
</plist>
